apple: 4.0
baked_potato: 5.0
beetroot: 1.0
beetroot_soup: 6.0
bread: 5.0
cake: 2.0
carrot: 3.0
chorus_fruit: 4.0
cooked_chicken: 6.0
cooked_cod: 5.0
cooked_mutton: 6.0
cooked_porkchop: 8.0
cooked_rabbit: 5.0
cooked_salmon: 6.0
cookie: 2.0
dried_kelp: 1.0
golden_apple: 4.0
enchanted_golden_apple: 4.0
golden_carrot: 6.0
melon_slice: 2.0
mushroom_stew: 6.0
poisonous_potato: 2.0
potato: 1.0
pufferfish: 1.0
pumpkin_pie: 8.0
rabbit_stew: 10.0
beef: 3.0
chicken: 2.0
cod: 2.0
mutton: 2.0
porkchop: 3.0
rabbit: 3.0
salmon: 2.0
rotten_flesh: 4.0
spider_eye: 2.0
cooked_beef: 8.0
tropical_fish: 1.0